# Generated by Django 5.1.4 on 2025-01-05 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100000000)),
                ("acceptance_rate", models.FloatField()),
                ("location", models.CharField(max_length=100000000)),
                ("tuition_out_of_state", models.FloatField()),
                ("high_school_gpa_w", models.FloatField()),
                ("high_school_gpa_uw", models.FloatField()),
                ("sat_reading", models.IntegerField()),
                ("sat_math", models.IntegerField()),
                ("act", models.IntegerField()),
                ("extracurr_awards", models.IntegerField()),
                ("score", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="NormalChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.TextField(max_length=1000000000000000000)),
            ],
        ),
        migrations.CreateModel(
            name="SchedChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.TextField(max_length=1000000000000000000)),
            ],
        ),
        migrations.CreateModel(
            name="TutorChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.TextField(max_length=1000000000000000000)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100000000)),
                ("email", models.CharField(max_length=100000000)),
                ("password", models.CharField(max_length=100000000)),
                ("salt", models.CharField(max_length=1023)),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("FR", "Freshman"),
                            ("SO", "Sophomore"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                        ],
                        default="FR",
                        max_length=5000,
                    ),
                ),
                ("schedules", models.TextField(max_length=100000000)),
                ("course_catalog", models.FileField(upload_to="media")),
                ("high_school_gpa_w", models.FloatField()),
                ("high_school_gpa_uw", models.FloatField()),
                ("sat_reading", models.IntegerField()),
                ("sat_math", models.IntegerField()),
                ("act", models.IntegerField()),
                ("chosen_major", models.CharField(max_length=100000000)),
                (
                    "college_level",
                    models.CharField(
                        choices=[
                            ("LT", "Low Tier"),
                            ("MT", "Mid Tier"),
                            ("TT", "Top Tier"),
                        ],
                        default="MT",
                        max_length=5000,
                    ),
                ),
                ("extracurr_awards", models.TextField(max_length=100000000)),
                ("notes", models.TextField(max_length=100000000)),
                ("score", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CollegeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("essays", models.BooleanField()),
                ("score_report", models.BooleanField()),
                ("sat_report", models.BooleanField()),
                ("additional_questions", models.BooleanField()),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.college"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.user"
                    ),
                ),
            ],
        ),
    ]
